name: Publish Docker image

on:
  release:
    types: [created]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: "Step 1: Create app, core, and captain folders."
        run: mkdir app core captain

      - name: "Step 2: Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '14'
    
      - name: "Step 3: Checkout pactum-flow-ui repo."
        uses: actions/checkout@v2
        with:
          repository: pactumjs/pactum-flow-ui

      - name: "Step 4: Build pactum-flow-ui, and copy the contents of dist folder into app folder."
        run: |
          npm install
          npm install -g @vue/cli
          npm run build
          cp -r dist/* app
      
      - name: "Step 5: Checkout pactum-flow-api repo."
        uses: actions/checkout@v2
        with:
          repository: pactumjs/pactum-flow-api

      - name: "Step 6: Copy the required contents of pactum-flow-api to core folder."
        run: cp -r package.json src core
      
      - name: "Step 7: Checkout pactum-flow-captain-api repo."
        uses: actions/checkout@v2
        with:
          repository: pactumjs/pactum-flow-captain-api
      
      - name: "Step 8: Copy the required contents of pactum-flow-captain-api to captain folder."
        run: cp -r package.json src captain

      - name: "Step 9: Check out the current(docker-pactum-flow) repo."
        uses: actions/checkout@v2
      
      - name: "Step 10: Log in to Docker Hub."
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: "Step 11: Extract metadata (tags, labels) for Docker."
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: asaianudeep/pactumjs
      
      - name: "Step 12: Build and push Docker image."
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}